# Generated by Django 3.1.4 on 2021-06-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('q1', models.CharField(max_length=3)),
                ('q2', models.CharField(max_length=3)),
                ('q3', models.CharField(max_length=3)),
            ],
        ),
    ]
