# Generated by Django 3.1.4 on 2021-06-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='medical_condition',
            fields=[
                ('mc', models.CharField(max_length=1000, primary_key=True, serialize=False)),
            ],
        ),
    ]
