# Generated by Django 3.1.4 on 2021-06-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_medical_condition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='medical_condition',
        ),
        migrations.AddField(
            model_name='client',
            name='mc',
            field=models.CharField(default='SOME STRING', max_length=1000),
        ),
    ]
