# Generated by Django 3.1.7 on 2021-06-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20210604_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='a',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='d',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='g',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='q4',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='q5',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='q6',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='q7',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='q8',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='q9',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='q1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='q2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='q3',
            field=models.IntegerField(null=True),
        ),
    ]
